 const palette={wood:'#cbaa76',metal:'#3d4747',floor:'#adada6',white:'#f1f0e8',glass:'#425963',bin:'#d1ddd6',gear:'#566548',rubber:'#242b2b',accent:'#7b3f38',background:'#fafbf6',foreground:'#25493c'};
 function token(name){return palette[name.replace('--garage-','').replace('--','')]||'#315845';}
 let seed=42;function random(){seed=(1664525*seed+1013904223)>>>0;return seed/4294967296;}
 function texture(kind){const c=document.createElement('canvas');c.width=256;c.height=kind==='wood'?1024:256;const ctx=c.getContext('2d'),im=ctx.createImageData(c.width,c.height);let stripes=Array.from({length:256},()=>random());
 for(let y=0;y<c.height;y++)for(let x=0;x<c.width;x++){const i=(y*c.width+x)*4;let n=random();let v=kind==='wood'?200+Math.sin(x*.63+Math.sin(y*.007)*2)*4+stripes[x]*8+n*3:kind==='fabric'?150+(x%3===0?20:0)+(y%3===0?18:0)+n*12:192+n*16;im.data[i]=v;im.data[i+1]=kind==='wood'?v*.87:v;im.data[i+2]=kind==='wood'?v*.68:v;im.data[i+3]=255;}ctx.putImageData(im,0,0);
 if(kind==='wood'){for(let k=0;k<4;k++){let x=30+random()*196,y=random()*1024;ctx.save();ctx.translate(x,y);ctx.scale(.65,2.7);for(let r=4;r<25;r+=3){ctx.strokeStyle='rgba(76,42,20,'+(0.12-r*.002)+')';ctx.beginPath();ctx.ellipse(0,0,r,r*.75,0,0,Math.PI*2);ctx.stroke();}ctx.restore();}}
 const t=new T.CanvasTexture(c);t.wrapS=t.wrapT=T.RepeatWrapping;t.colorSpace=T.SRGBColorSpace;t.anisotropy=renderer.capabilities.getMaxAnisotropy();return t;}
 const woodMap=texture('wood'),floorMap=texture('floor'),fabricMap=texture('fabric');floorMap.repeat.set(3,6);fabricMap.repeat.set(6,9);
 function mat(key){const p={color:palette[key],roughness:.7,metalness:0,envMapIntensity:.45};if(key==='wood'){p.color='#f4d5a7';p.map=woodMap;p.bumpMap=woodMap;p.bumpScale=.002;p.roughness=.88;}if(key==='floor'){p.map=floorMap;p.bumpMap=floorMap;p.bumpScale=.0003;p.roughness=.96;}if(key==='white'){p.roughness=.32;p.metalness=.18;p.envMapIntensity=.6;}if(key==='metal'){p.roughness=.34;p.metalness=.72;}if(key==='bin'){p.roughness=.24;p.metalness=.05;}if(key==='glass'){p.roughness=.13;p.metalness=.45;}return new T.MeshStandardMaterial(p);}
 function fabricMaterial(key){const m=materials[key].clone();m.map=fabricMap;m.bumpMap=fabricMap;m.bumpScale=.003;m.roughness=.97;return m;}
